#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 17 13:45:02 2023

@author: aidenhensel
"""

def menu():
    print('Menu\n-------------\n1. Encode\n2. Decode\n3. Quit')

def encode(stor):
    password=''
    for i in stor:
        num = int(i) + 3
        if num >= 10:
            num -= 10
        password += f'{num}'
    return password
    
def main():
    i=1
    stor=0
    while i!=0:
        menu()
        sel=int(input('Please enter an option:'))
        if sel==1:
            stor=input('Please enter your password to encode:')
            new_pass=encode(stor)
            print('Your password has been encoded and stored!')
        if sel == 3:
            i=0
        if 0>= sel >= 4:
            print('Choose a valid option.')

if __name__ == '__main__':
    main()
